# 100 tane mizahi, yaratıcı ve eğlenceli Türkçe "küfür/hakaret" cümlesi
kufurler = [
    "Sana zeki dediler de, beynin tatilde miydi o sırada?",
    "Senin karizman, bozuk para kadar bile etmez!",
    "Aklın o kadar kısa ki, selfie çubuğu bile yetişemez!",
    "Senin zekanla anca kapı zili çalarsın!",
    "Beyninin yarısı tatilde, diğer yarısı kayıp!",
    "Senin muhabbetin, bayat ekmek gibi tatsız!",
    "Klavye başında aslansın, ama gerçek hayatta kedi yavrusu!",
    "Senin esprin, buzdolabında bile donmaz!",
    "Aklın o kadar yavaş ki, kaplumbağa seni sollar!",
    "Senin muhabbetinle anca uyku ilacı yapılır!",
    "Beyninin hızı, 56K modemden bile yavaş!",
    "Sana cool dediler, ama sen bildiğin soba borusu!",
    "Senin zekan, bozuk ampul kadar bile parlamaz!",
    "Klavye kahramanı, gerçek hayatta fare!",
    "Senin muhabbetin, bozuk radyo gibi cızırdıyor!",
    "Aklın o kadar kıt ki, anca kibrit kutusuna sığar!",
    "Sana karizmatik dediler, ama aynaya mı baksan acaba?",
    "Senin esprin, çöldeki kum tanesi kadar kuru!",
    "Beyninin pili bitmiş, şarj cihazın da kayıp!",
    "Senin muhabbetin, bozuk saat gibi yerinde sayıyor!",
    "Aklın o kadar kısa ki, cetvelle ölçülmez!",
    "Sana zeki dediler, ama sen anca kopyala-yapıştır yaparsın!",
    "Senin karizman, eski model telefon kadar demode!",
    "Beyninin depolama alanı, 2 MB’tan fazla değil!",
    "Senin muhabbetin, bozuk plak gibi takılıp duruyor!",
    "Aklın o kadar küçük ki, mikroskopla bile zor görünür!",
    "Sana havalı dediler, ama sen bildiğin vantilatör!",
    "Senin esprin, bayat simit kadar bile tat vermez!",
    "Beyninin hızı, salyangoz yarışında sonuncu gelir!",
    "Senin muhabbetin, bozuk musluk gibi damlıyor!",
    "Aklın o kadar zayıf ki, anca Wi-Fi sinyali çeker!",
    "Sana cool dediler, ama sen donmuş kola gibisin!",
    "Senin zekan, karanlıkta kaybolmuş fener gibi!",
    "Beyninin şarjı bitmiş, powerbank de yanmış!",
    "Senin muhabbetin, eski gazete kadar bayat!",
    "Aklın o kadar kısa ki, anca kısa mesaj atarsın!",
    "Sana karizmatik dediler, ama sen bildiğin karikatür!",
    "Senin esprin, bozuk oyuncak kadar bile eğlenceli değil!",
    "Beyninin kapasitesi, flash bellekten bile düşük!",
    "Senin muhabbetin, bozuk televizyon gibi karıncalı!",
    "Aklın o kadar yavaş ki, takoz bile seni geçer!",
    "Sana havalı dediler, ama sen bildiğin balon!",
    "Senin zekan, bozuk hesap makinesi kadar işe yaramaz!",
    "Beyninin bağlantısı kopmuş, modeme reset lazım!",
    "Senin muhabbetin, bozuk zil gibi tıkırdıyor!",
    "Aklın o kadar küçük ki, cebine bile sığmaz!",
    "Sana zeki dediler, ama sen anca bulmaca çözersin!",
    "Senin karizman, eski kaset kadar nostaljik!",
    "Beyninin hızı, bisikletle yarışan araba gibi!",
    "Senin muhabbetin, bozuk fırın gibi ısıtmıyor!",
    "Aklın o kadar kısa ki, anca kısa film çekersin!",
    "Sana cool dediler, ama sen bildiğin dondurma!",
    "Senin esprin, bozuk şemsiye kadar işe yaramaz!",
    "Beyninin pili bitmiş, yedek pil de yok!",
    "Senin muhabbetin, eski model araba gibi tekliyor!",
    "Aklın o kadar zayıf ki, anca zayıf Wi-Fi çeker!",
    "Sana karizmatik dediler, ama sen bildiğin emoji!",
    "Senin zekan, bozuk saat kadar bile tutarlı değil!",
    "Beyninin bağlantısı kopmuş, kablo da kayıp!",
    "Senin muhabbetin, bozuk hoparlör gibi cızırtılı!",
    "Aklın o kadar küçük ki, anca nokta kadar yer kaplar!",
    "Sana havalı dediler, ama sen bildiğin helyum balonu!",
    "Senin esprin, bozuk lamba kadar bile ışık vermez!",
    "Beyninin hızı, yürüyen merdiven kadar bile değil!",
    "Senin muhabbetin, bozuk kalem gibi yazmıyor!",
    "Aklın o kadar kısa ki, anca kısa çöp yakarsın!",
    "Sana zeki dediler, ama sen anca Google’a sorarsın!",
    "Senin karizman, eski sandalye kadar bile sağlam değil!",
    "Beyninin depolama alanı, disketten bile küçük!",
    "Senin muhabbetin, bozuk telefon gibi çekmiyor!",
    "Aklın o kadar yavaş ki, anca yaya geçidinde kalırsın!",
    "Sana cool dediler, ama sen bildiğin buzdolabı!",
    "Senin zekan, bozuk priz kadar bile enerji vermez!",
    "Beyninin şarjı bitmiş, priz de bozuk!",
    "Senin muhabbetin, eski çorap kadar bile tatlı değil!",
    "Aklın o kadar küçük ki, anca pixel kadar yer kaplar!",
    "Sana karizmatik dediler, ama sen bildiğin sticker!",
    "Senin esprin, bozuk kilit kadar bile açılmaz!",
    "Beyninin hızı, kapı gıcırtısından bile yavaş!",
    "Senin muhabbetin, bozuk bulaşık makinesi gibi çalışıyor!",
    "Aklın o kadar kısa ki, anca kısa devre yaparsın!",
    "Sana havalı dediler, ama sen bildiğin pervane!",
    "Senin zekan, bozuk termostat kadar bile tutarlı değil!",
    "Beyninin bağlantısı kopmuş, router da yanmış!",
    "Senin muhabbetin, bozuk mikrofon gibi yankı yapıyor!",
    "Aklın o kadar zayıf ki, anca zayıf sinyal çeker!",
    "Sana cool dediler, ama sen bildiğin buz kalıbı!",
    "Senin esprin, bozuk zippo gibi ateş yakmaz!",
    "Beyninin pili bitmiş, şarj kablosu da kopuk!",
    "Senin muhabbetin, eski defter kadar bile ilginç değil!",
    "Aklın o kadar kısa ki, anca kısa metraj film çekersin!",
    "Sana zeki dediler, ama sen anca yapboz yaparsın!",
    "Senin karizman, bozuk sandalye kadar bile dayanmaz!",
    "Beyninin hızı, eski daktilodan bile yavaş!",
    "Senin muhabbetin, bozuk projektör gibi bulanık!",
    "Aklın o kadar küçük ki, anca minyatür model olur!",
    "Sana havalı dediler, ama sen bildiğin fan motoru!",
    "Ağzını burnunu dağıtırım",
    "Ağzını yırtarım",
    "Aklını alırım",
    "Ameliyat ederim",
    "Seni eşşek sudan gelene kadar dövecem",
    "Aptal",
    "Arkana adam takarım",
    "Artist",
    "Asarım keserim",
    "Aşağılık kadın",
    "Ateşin başına vurdu",
    "Ayağa düşürürüm",
    "Ayı",
    "Azgın",
    "Bacaklarını kırarım",
    "Benim kölemsin",
    "Beyinsiz",
    "Bıçağı al karnına sok",
    "Bilgisiz",
    "Boğazını kesecem",
    "Cahil",
    "Çerçeveni dağıtırım",
    "Çirkin",
    "Çürük kadın",
    "Çürümüşsün",
    "Dadı",
    "Dağa kaldırırım",
    "Davul olasın",
    "Dayaktan öldürürüm",
    "Deli",
    "Domuz",
    "Dostundan geliyorsun",
    "Dümbüğün kızı",
    "Dümbük",
    "Dünyanın o...su",
    "Eksik etek",
    "Elimde kalırsın",
    "Eşek",
    "Eşek çobanı",
    "Eşeklik yaptım evlendim",
    "Eşyasın",
    "Eteğine ettiğimin karısı",
    "Façanı aşağı alırım",
    "Fahişe",
    "Gavurun dölü",
    "Geri zekalı",
    "Görgüsüz",
    "Gözünü keserim",
    "Hayvan",
    "Hoşt",
    "Kafanı gözünü kırarim",
    "Kahpe",
    "Kahpe yapacam sizi",
    "Kaltak",
    "Kancık",
    "Kanı bozuk",
    "Karnını deşerim",
    "Kavatın kızı",
    "Kepaze",
    "Kızışmış",
    "Kimden peydahladın",
    "Kime veriyorsun",
    "Komaya sokarım",
    "Kopartacam",
    "Kölemsin",
    "Köpek",
    "Köpekler de doğuruyor",
    "Kötü yola düşesin",
    "Kullanıcam seni",
    "Kuru",
    "Kuş beyinli",
    "Lan",
    "Manyak",
    "Mezarına tükürmem",
    "Mikrop",
    "Öl geber",
    "Pasaklı",
    "Pavyon karısı",
    "Pavyona mı düşecen",
    "Pısırık",
    "Piç",
    "Psikopat",
    "Puşt",
    "Saçaklı",
    "Salak",
    "Salaklaşma",
    "Sapık",
    "Seni ahıra bile sokmam",
    "Seni çizerim",
    "Seni döverim",
    "Seni kim naapsın",
    "Seni kötü yola düşürecem",
    "Seni öyle bir döverim",
    "Seni takip ederim",
    "Seni rezil ederim",
    "Seni vuracam",
    "Sokak sürtüğü",
    "Süprüntü",
    "Sürtük",
    "Sütü bozuk",
    "Şerefsiz",
    "Şeyin başına vurdu",
    "Şırfıntı",
    "Şirret",
    "Ulan karı",
    "Uyuz",
    "Yakalarsam seni satacam"
]


